export default {
  MYPROFILE: "My Profile",
  EDITPROFILE: "EditProfile",
  PROFILE: "Profile",
  GROUPS: "Groups",
  MESSAGE: "Message",
  HOME: "Home",
  ALLAN: "Allan Gonzalez",
  EXAMPLE: "example@gmail.com",
  PERCENT: "80%",
  COMPLETE: " Complete",
  SUMMARY: "Summary",
  IDENTITY: "Identity",
  VENTICULAR: "Ventricular Septal Defect",
  DESCRIPTION: "Description",
  CONDITION: "Condition",
  HEALTH: "Health Story",
  NO: "No",
  INTEREST: "Interests",
  SHORT_TERM: "Short term goals",
  LEARN: " Learn what to expect from Surgery",
  CONTACT: "Contact Us",
  TERMS: "Terms and conditions",
  LOGOUT: "Logout",
  EDIT_DETAILS: "Edit Personal Details",
  FULL_NAME: "Full Name",
  SALLIE: " Sallie Johnson",
  DOB: "Date of Birth",
  DOB_NUM: "24-10-1997",
  ADDRESS: "Address",
  FULL_ADDRESS: "8236 Rockaway Avenue, NC 27405",
  SEX: "Sex",
  GENDER: "Male",
  PASSWORD: "Password",
  SECURITY_PASSWORD: "************",
  CHANGE_PASSWORD: "Change Password",
  EDIT_SUMMARY: "Edit Summery",
};
